### ISSUE TITLE
Keys Don't Work

### ISSUE THREAD

**Issue by actuallyfarquaad** [PenguScript/pengu_gruppe6delivery#21]
I dont know why, but they keys dont work when the stockade spawns. It says in the config:

-- Looking for GiveKeys config?
-- Check: config_cl.lua

But that file doesn't exist. How do I fix this?

**Comment by Sharpbeard** [comment]
Add this line underneath line 260 in the delivery.lua at the StartFirstJob event:
local plate = args["plate"]

**Comment by PenguScript** [comment]
Should be fixed.
