### ISSUE TITLE
Unable to use ox_fuel

### ISSUE THREAD

**Issue by TaakoOfficial** [PenguScript/pengu_gruppe6delivery#22]
SCRIPT ERROR: @pengu_gruppe6delivery/client/delivery.lua:268: No such export SetFuel in resource ox_fuel

**Comment by PenguScript** [comment]
That'd be because its a different export needed for that resource. Check their documentation and the error line will be the line to replace with their export

**Comment by TaakoOfficial** [comment]
Yes I set their export still no luck

**Comment by TaakoOfficial** [comment]
`if IsPedSittingInAnyVehicle(cache.ped or PlayerPedId()) then
        --exports[Config.FuelResource]:SetFuel(GetVehiclePedIsIn(cache.ped or PlayerPedId()), 100)
        Entity(stockade).state.fuel = 100 
        TriggerEvent('pengu_gruppe6delivery:RecieveDestinationOne', GetVehiclePedIsIn(cache.ped or PlayerPedId()))
    end`
