### ISSUE TITLE
Fuel doesn't get added with ps-fuel

### ISSUE THREAD

**Issue by 0llz** [PenguScript/pengu_gruppe6delivery#5]
Fuel doesn't get added with ps-fuel says no entity found. Tried using Wait(500) to give it some time to find the entity but can't seem to get it working some reason :/

**Comment by PenguScript** [comment]
Try again on this update! [(v1.0.4)](https://github.com/PenguScript/pengu_gruppe6delivery/releases/tag/v1.0.4)
