### ISSUE TITLE
ps-inventory

### ISSUE THREAD

**Issue by SmokerADHD** [PenguScript/pengu_gruppe6delivery#6]
it dosen't remove the items when delivered so i have like a full inventory of million bags and they dont have any value all undifined

**Comment by PenguScript** [comment]
I hear ya. We're fixing this in the upcoming revamp! Go back to v1.0.3 for now. apologies!

**Comment by SmokerADHD** [comment]
oh okay thank you for the hardwork!

**Comment by PenguScript** [comment]
Should be fixed
